### ISSUE TITLE
--reset flag for initial db creation

### ISSUE THREAD

**Issue by salva-imm** [itsumura-h/nim-allographer#174]
Hey,
do we need `--reset` for initial db creation? 
i ran my models (Schema) without `--reset` , it does nothing but creates an empty file with sqlite format!(there's no table or field in there)

I'm running examples

nim version: `1.4.8`
allographer version: `0.19.2`

**Comment by itsumura-h** [comment]
@salva-imm 
Let's create a table named `users` in a new environment. The `users` table will be created in the Sqlite file and at the same time the sql that created the users table will be recorded in the `.migration.json` file.

When we run the migration again, the .migration.json file will have a record of the creation of the users table, so the migration will not be executed. This is because the sql recorded in the `.migration.json` file and the sql output by schema builder are the same.

At this point, you can add the `--reset` flag to ignore the `.migration.json` and run the migration again.
